# Generated by Django 5.2.1 on 2025-05-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientappointment',
            old_name='appointment_date',
            new_name='booking_date',
        ),
        migrations.AlterUniqueTogether(
            name='patientappointment',
            unique_together={('doctor', 'booking_date', 'timeslot')},
        ),
    ]
