# Generated by Django 5.2.1 on 2025-05-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_appointment_date_patientappointment_booking_date_and_more'),
        ('doctors', '0002_timeslot_is_booked'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientappointment',
            unique_together={('doctor', 'booking_date', 'timeslot', 'patient')},
        ),
    ]
