# Generated by Django 5.2.1 on 2025-06-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_patientappointment_unique_together'),
        ('doctors', '0003_alter_doctors_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientappointment',
            unique_together={('doctor', 'timeslot')},
        ),
    ]
